# select CAR_ID, ROUND(AVG(end_date - start_date + 1),2) AS AVERAGE_DURATION from CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# HAVING AVERAGE_DURATION >= 7
# ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

select CAR_ID, ROUND(AVG(timestampdiff(day, start_date, end_date)+1),1) AS AVERAGE_DURATION from CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
